### ISSUE TITLE
Confusing model versions

### ISSUE THREAD

**Issue by cdebuck** [tibbdc/ECMpy#6]
Hello,

Thank you for developing this package. I had a question concerning the different versions of the EC-GEM E. coli model, as I would like to use the E. coli model for some analyses.
In the model folder, there are two files: 'eciML1515.json' and 'iML1515_irr_enz_constraint_adj.json'. Based on the suppl data from your paper I can deduce that eciML1515.json is the final model version (since it has a growth rate 0.68 h-1).
However, it is confusing that scripts 03 and 04 respectively create and use the iML1515_irr_enz_constraint_adj model, while script 05 uses the eciML1515. Why are the analyses in script 04 performed with the iML1515_irr_enz_constraint_adj model? Could it perhaps be made more explicit which model file is final (and the correct one to use) in the Readme?

**Comment by maozhitao** [comment]
I apologize for the confusion. If you're using it for biological simulations, please use 'eciML1515.json'. This model represents the final E. coli model from our published paper (http://dx.doi.org/10.3390/biom12010065), incorporating manual corrections based on experimental results. 'iML1515_irr_enz_constraint_adj.json' is an enzymatic constrained model, built automatically using notebooks 02 and 03 with ECMpy2.0. Notebook 4 involves a general analysis process for enzyme-constrained models, so both 'eciML1515.json' and 'iML1515_irr_enz_constraint_adj.json' can be used. Notebook 05 applies this enzyme-constrained model to real metabolic engineering modifications, hence utilizing the manually corrected model rather than the automatically generated one.

**Comment by cdebuck** [comment]
That's clear, thank you!
